/** Claves estables de plantilla (metadatos / ledger / tags). */
export type TransactionalTemplateKey =
  | "platform_user_invited"
  | "platform_user_security_notice"
  | "registration_verification_otp"
  | "registration_payment_confirmation"
  | "platform_mfa_lockout_notice"
  | "platform_admin_session_started"
  | "workspace_billing_grace_started"
  | "workspace_billing_suspension_approaching"
  | "workspace_billing_suspended_non_payment"
  | "workspace_billing_recovered"
  | "workspace_payment_receipt"
  | "registered_user_password_reset"
  | "platform_admin_password_reset"
  | "workspace_member_added"
  | "workspace_invitation_sent"
  | "workspace_invitation_accepted"
  | "workspace_invitation_revoked"
