/**
 * v1: Coef. de variación (σ/μ) y regla auxiliar (max-min)/max(μ,ε) — contracts-docs.
 */
export const PREDICTABILITY_COV_ELEVATED = 0.35
export const PREDICTABILITY_RANGE_RATIO_ELEVATED = 0.5
export const PREDICTABILITY_COVERAGE_EPS = 0.000_001

export const PREDICTABILITY_DEFAULT_LAST_N = 6

export const DataQualityWarningCode = {
  NO_LINKED_PROJECTS: "NO_LINKED_PROJECTS",
  METHODOLOGY_MIX: "METHODOLOGY_MIX",
  INSUFFICIENT_PERIOD_HISTORY: "INSUFFICIENT_PERIOD_HISTORY",
  LIMITED_PERIOD_HISTORY: "LIMITED_PERIOD_HISTORY",
  SPRINT_METRICS_SKIP_LEGACY: "SPRINT_METRICS_SKIP_LEGACY",
  KANBAN_THROUGHPUT_AUDIT: "KANBAN_THROUGHPUT_AUDIT_GAPS",
  MULTI_SOURCE_SCRUM: "MULTI_SOURCE_SCRUM_SPRINTS",
  KANBAN_MULTI_PROJECT_WEEKS: "KANBAN_MULTI_PROJECT_WEEKS_AGGREGATED",
} as const
